server:
  port: 2025

spring:
  application:
    name: clgportal
    version: v1

  banner:
    location: classpath:banner.txt

  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html

profile:
  pic: profilePics/

file:
  upload-dir: uploads

recaptcha:
  secret:
    key: ${CAPTCHA_SECRET}
  verify:
    url: ${CAPTCHA_VERIFY_URL}